title: RGVA Conference Deadlines
description: Countdowns to top CV/NLP/ML/AI/EduTech/PatentRetrieval conference deadlines
author: Abhishek Das

domain: "https://rgva-deadlines.github.io"
baseurl: ""

twitter_hashtag: machinelearning
github_username: rgva-deadlines
github_repo: rgva-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
